spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/video?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 1024MB
      max-file-size: 1024MB

mybatis:
  type-aliases-package: com.hu.video.entity
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#thymeleaf
thymeleaf:
  prefix: classpath:/templates/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5


#沙箱支付配置
alipay:
  appId: 9021000123603553
  appPrivateKey: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQC55P6YfO3Bh7D2b0Z/n4KOnkOhPY4XUV5c0eHNpLhMsFbv2Tna637a+S7I03KZZd+jB1IhDE2OZnYyvlaw9WoEfxPcdhbEErW8ZfdSc6TliZ5sA8TvhJD/HuyVf8IgNFNQ532QlbubDM5ZT2tERbKFIhwnrTo7ENNLyI7JfdTLhlqGGlbVCqJ7SUxW0mb03Z/FsuUfT4LHcyNi/xxZ5X+qNRBRambBApUYn84+Eqv6BV9U6uNhp2g72qGF8he0KKSx4yJfTi32mkss1eGdLNblJ6o41FvPicEn6qthIvabpS8jSTApJP95Yx6vY3fQ418VN0F5eQ0fwujupPmJYLfTAgMBAAECggEBAK/ZvC4sIA2veuvkn+Ai2LJpbLifLkdIpedQdDbA18dUGSmTaHN7yukCSAuaWxJZmJD0X/D7XnKS4sVl4URNJBlUzUkEPM0Glfy+yJOq6hZpdP/hIO8jjLaKXmueC9nDJf2mvtWDj5FBMAK0aliPRi1C8zdlW2x8oiVSeCCLdD2CH+iCrJfyOXxNY1OKnQDPEfE3NK0DBzrx2id06/E9D182IHpOXdsfl75Xg2y26P4HEonTlmZS+itsQNXcn5UkEJY8QpkdRWB8EOogsHvsX3Msxjhr5MH8ixM9Di/sDkLU0Tf58aNAiBUkXuo4zYT9y9a5kjcvX5KVS8ZtFnLjnGECgYEA85zuCJb01mKB20CNfK/bMNWPzDPuk85HjvYmhsUNtGrcF3U06XJVi16gvSqW12jVVxpIvY+HkHlpBNs/huGgtocLaC6jBn64QuNC1aUrWhHY0e5sSJvQnvsCQR989TOHa42yIrTDO55U6XA4/a9hqkD5azoXvop0zu4mdwHKjT0CgYEAw1jAqJSsVDzTAVxgbjYYG+vjLzu4MV1CjPh0A3pYYLXeZjf/8KhCW61H+5pSCOgAcZrjBr560UZfhks0ofW/QXyyypo/PK+F/ic+u3HmL/CTVf+CRDNnayY3xjhbRc8a0uBAUGkPBEQNreCsFqxnD4oS0n67xtp1gHnK+xrxyk8CgYEAiy62pHuyqKWhMWYBMCK85XqubGmjPhkVsy0ZN9hviwuecVyKfXHQRA8tYMZrZejEMr6Wno7ZUga7pIWrFuHj00T2lHBIvhY6KiTzc2KpkQ0vRkmk3hr/p0UbtZ9K4kCtdxp+kuuZu38rXi+6r926u+3hUozfMgKi1/MiUM3aLrUCgYEAsSZDUJ3CyYF/OLS1Hj0gD/ISzDq0BtA0EfMeAilpDArh7IDMMUnlI444wQppano6LMvxJaSHbFENP5Pj3xwknRagbOsEfdwO/zRHx2S7Aq6AbnSPhZm4J4s4+SESZHQ0Nxf2OvWLEKtGXHBqnwUpUQY9m3Yig2qJNEE+ugjtTDECgYEAnrUlqPIGdL5gBV8QIRrcJTqkDkg37WD0WzQEKNRZ8+BRvzsQ1nOmzrTkTijlTIIPpI0PwIArqcJUWAgSqkfujVYBnoItTdAgi3cfMm60PF8wz12Rj1nCFfaPGLjZuXxm7D3u4FMjjz327qj5R2rxdRwWBwCdwaaa82o3dPC0JAQ=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApTN/eP1Bmo8eP73dHdtjkAOAdyZCKVCEYsFYkr/UrJp0VTMaqbsGik8iz+7P/kbAjtx3TdgPjfujf+p1MT4hQRcJ13m4T+Kq3TB1mYIL9AWFBS1OWYTMa9S2BaGPrWZMQSMxgfSHZPSgSBh3zSXCUycmAXJJ6PwWnF0tf6k9VfdulnN6Jla8G/iQ60zrDwrxjHf/Vlp4tojfXjPc25J0pR2jk8sldvq5QH+gAVADG9XrK3yOCDRfJ3DeAyQegnNalIbqS6ejqOr4VtwdnoJ9V3rUyn6GBEL79wCgY8MgtXdM+qAeYGOyz7QOqOtxE3HpcV8j6tluBVsflYFm2CCBYQIDAQAB
  notifyUrl:       http://zfftuf.natappfree.cc/alipay/notify
